kuechengeister/reports/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('reports.views',
    url(r'^$', 'index', name='index'),
    url(r'^day-report/$', 'day_report', name='report_day'),
    url(r'^week-report/$', 'week_report', name='report_week'),
    url(r'^week-compact-report/$', 'week_report_compact',
        name='report_week_compact'),
    url(r'^month-report-stats/$', 'month_report_stats',
        name='report_month_stats'),
    url(r'^somic/$', 'somic'),
    url(r'^hytera/$', 'hytera'),
    url(r'^diamant3-buch/$', 'diamant3_export_buch', name='diamant3_export_buch'),
    url(r'^diamant3-stamm/$', 'diamant3_export_stamm', name='diamant3_export_stamm'),
    url(r'^datev-buch/$', 'datev_export_buch', name='datev_export_buch'),
    url(r'^datev-stamm/$', 'datev_export_stamm', name='datev_export_stamm'),
)

kuechengeister/urls.py
from django.conf.urls.defaults import include, patterns, url
from django.conf import settings
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^chaining/', include('smart_selects.urls')),
    (r'^$', 'kg.views_index.index'),
    (r'^menueprint/$', 'kg.views_index.menue_print'),
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGOUT_REDIRECT_URL}),
    (r'^passwort/$', 'kg.views_registrierung.password_lost'),
    (r'^passwort/erfolg/$', 'kg.views_registrierung.password_success'),
    (r'^passwort/fehler/$', 'kg.views_registrierung.password_error'),
    (r'^passwort/aktivierung/$', 'kg.views_registrierung.password_changed'),
    (r'^kunden/$', 'kg.views_kunden.index'),
    (r'^kunden/essen/$', 'kg.views_kunden.essen'),
    (r'^kunden/essen/(?P<year>\d{4})/(?P<week>\d{1,2})/$', 'kg.views_kunden.essen'),
    (r'^kunden/brotzeit/$', 'kg.views_kunden.brotzeit'),
    (r'^kunden/brotzeit/(?P<year>\d{4})/(?P<week>\d{1,2})/$', 'kg.views_kunden.brotzeit'),
    (r'^kunden/kinder/$', 'kg.views_kunden.kinder'),
    (r'^kunden/kinder/edit/(?P<child_id>\d+)/$', 'kg.views_kunden.kinder_edit'),
    (r'^kunden/kinder/add/$', 'kg.views_kunden.kinder_add'),
    (r'^kunden/profil/$', 'kg.views_kunden.profil'),
    (r'^kunden/profil/edit/$', 'kg.views_kunden.profil_edit'),
    (r'^kunden/profil/zahlungsart/$', 'kg.views_kunden.paytype_edit'),
    (r'^kunden/profil/sepa/$', 'kg.views_kunden.sepa_mandate_edit'),
    (r'^kunden/passwort/$', 'kg.views_kunden.password_change'),
    (r'^kunden/abo/$', 'kg.views_kunden.abo'),
    (r'^kunden/abo/edit/(?P<child_id>\d+)/$', 'kg.views_kunden.abo_edit'),
    (r'^kunden/rechnungen/$', 'kg.views_kunden.rechnungen'),
    (r'^kunden/rechnungen/papier$', 'kg.views_kunden.rechnungen_papier'),
    (r'^kunden/rechnungen/(?P<invoice_name>[a-zA-Z0-9_\.]+)$', 'kg.views_kunden.rechnungen_download'),
    (r'^kunden/guthaben/$', 'kg.views_kunden.guthaben'),
    (r'^kunden/guthaben/aufladen/$', 'kg.views_kunden.guthaben_aufladen'),
    (r'^kunden/guthaben/minimum/$', 'kg.views_kunden.guthaben_minimum'),
    (r'^kunden/abwesenheit/', include('absence.urls', namespace='absence')),

    (r'^registrierung/neukunde/$', 'kg.views_registrierung.neuanmeldung'),
    (r'^registrierung/neukunde/erfolg/$', 'kg.views_registrierung.neuanmeldung_success'),
    (r'^registrierung/neukunde/fehler/$', 'kg.views_registrierung.neuanmeldung_error'),
    (r'^registrierung/bestandskunde/$', 'kg.views_registrierung.registrierung'),
    (r'^registrierung/bestandskunde/erfolg/$', 'kg.views_registrierung.registrierung_success'),
    (r'^registrierung/bestandskunde/fehler/$', 'kg.views_registrierung.registrierung_error'),

    (r'^api/pull_pos_data/$', 'kg.views_api.pull_pos_data'),
    (r'^api/push_pos_data/$', 'kg.views_api.push_pos_data'),
    (r'^api/push_pos_data_v2/$', 'kg.views_api.push_pos_data_v2'),

    url(r'^admin/$', 'kg.views_admin.index', name='admin_index'),
    (r'^admin/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^admin/kg/statistik/$', 'kg.views_admin.statistik_index'),
    (r'^admin/kg/statistik/reduction/$', 'kg.views_admin.statistik_reduction'),
    (r'^admin/kg/rechnung/$', 'kg.views_admin.rechnung_index'),
    (r'^admin/kg/rechnung/download/$', 'kg.views_admin.rechnung_download'),
    (r'^admin/kg/rechnung/abrechnung/$', 'kg.views_admin.rechnung_abrechnung'),
    (r'^admin/kg/sepadebitdownload/download/(?P<download_id>\d+)/(?P<sequence_type>[a-zA-Z]{4})$', 'kg.views_admin.sepa_debit_download'),
    url(r'^admin/kg/order/', 'kg.views_admin.order_index', name='admin_order'),
    (r'^admin/kg/flatrate/', 'kg.views_admin.flatrate_index'),
    (r'^admin/kg/mailtest/', 'kg.views_admin.mailtest_index'),
    (r'^admin/kg/backup/$', 'kg.views_admin.csv_backup'),
    (r'^admin/kg/emailexport/$', 'kg.views_admin.email_export'),
    (r'^admin/kg/csvupload/$', 'kg.views_admin.bank_csv_upload'),
    (r'^admin/kg/importposdata/$', 'kg.views_admin.import_pos_app_data'),
    (r'^admin/kg/bankaccounttransaction/automatching/', 'kg.views_admin.bat_auto_matching'),
    (r'^admin/kg/bankaccounttransaction/manualmatching/', 'kg.views_admin.bat_manual_matching'),
    (r'^admin/kg/actionlogshortlist/$', 'kg.views_admin.actionlog_short_list'),
    (r'^admin/kg/orderhistory-popup/(?P<child_id>\d+)/(?P<menu_id>\d+)/$', 'kg.views_admin.orderhistory_popup'),
    (r'^admin/kg/orderhistory/(?P<child_id>\d+)/(?P<year>\d{4})/(?P<month>\d{1,2})/$', 'kg.views_admin.orderhistory'),
    (r'^admin/kg/essenmarken/', 'kg.views_admin.voucher_index'),
    (r'^admin/kg/fibuexport_esl/', 'kg.views_admin.fibuexport_esl'),
    (r'^admin/kg/somic_metzgerei/', 'kg.views_admin.somic_metzgerei_index'),
    (r'^admin/kg/somic_fibu/', 'kg.views_admin.somic_fibu_index'),
    (r'^admin/kg/kobrow_monatsbericht/', 'kg.views_admin.kobrow_monthly_report'),
    (r'^admin/kg/svmv_create_sepa_debits/', 'kg.views_admin.svmv_create_sepa_debits'),
    url(r'^admin/reports/', include('reports.urls', namespace='reports')),
    # bank_transaction app urls
    (r'^admin/bank_transactions/load_transactions/', 'bank_transactions.views_admin.load_transactions'),
    # customer_login urls
    (r'^admin/customer_login/', 'kg.views_admin.customer_login'),
    (r'^admin/change_customer_login/', 'kg.views_admin.change_customer_login'),
    (r'^admin/random_password/', 'kg.views_admin.random_password'),
    (r'^admin/change_customer_password/', 'kg.views_admin.change_customer_password'),
    (r'^admin/delete_customer_login/', 'kg.views_admin.delete_customer_login'),
    url(r'^admin/celery/query_task', 'kg.views_admin.query_task_result',
        name='celery_task_result'),
    (r'^admin/', include(admin.site.urls)),

    # Uncomment the next line to enable the admin:
    url(r'^nested_admin/', include('nested_admin.urls')),
    # url(r'^api/', include('api.urls'))
    url(r'^tinymce/', include('tinymce.urls')),
)

kuechengeister/absence/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now


class Absence(models.Model):
    """Model for the single absence of a child. It could for a day or more."""
    child = models.ForeignKey('kg.child', verbose_name=u'Kind')
    date_from = models.DateField(verbose_name=u'Datum von')
    date_to = models.DateField(
        verbose_name=u'Datum bis', blank=True, null=True)
    notice = models.TextField(verbose_name=u'Mitteilung')

    class Meta:
        ordering = ['-date_from', 'child__name', 'child__surname']
        verbose_name = "Abwesenheit"
        verbose_name_plural = "Abwesenheit"

    def __unicode__(self):
        return '%s (%s - %s) ' % (self.child, self.date_from, self.date_to)

    def save(self, *args, **kwargs):
        """If date_to is missing, it will take the date_from."""
        if not self.date_to and self.date_from is not None:
            self.date_to = self.date_from
        return super(Absence, self).save(*args, **kwargs)

    @property
    def editable(self):
        return now().date() < self.date_from

kuechengeister/templates/kg/admin/actionlog_short_list.html
{% load fieldtags %}


<ul class="actionlist">

    {% for logEntry in logEntries %}


        <li>
            <span class="mini quiet">{{ logEntry.action_time }}</span>
            <br />
            <span style="{{ logEntry.style }}">{{ logEntry.change_message }}</span>
        </li>

    {% endfor %}

        <li>
            <br />
            <a href="/admin/kg/actionlog">weitere</a>
        </li>

</ul>

kuechengeister/templates/kg/admin/customer_login_deleted.html
<span class="success">Login gelöscht</span>
<button id="btn_close">Schließen</button>

kuechengeister/templates/kg/admin/existing_customer_login.html
<span id="btn_change_username" class="btn_custom_tab{% if visible == 'change_username' %} selected{% endif %}">Benutzername ändern</span>
<span id="btn_change_password" class="btn_custom_tab{% if visible == 'change_password' %} selected{% endif %}">Passwort ändern</span>
<span id="btn_delete_login" class="btn_custom_tab{% if visible == 'delete_login' %} selected{% endif %}">Login löschen</span>
<div id="change_username" class="custom_tab{% if visible != 'change_username' %} invisible{% endif %}">
    {% if username_changed %}
        <span class="success">Benutzername geändert</span>
    {% endif %}
    <form action="" method="post" id="change_customer_login">
        {% if username_taken %}
            <span class="error">Benutzername "{{ username_taken }}" ist schon vergeben.</span>
        {% endif %}
        {% if username_to_short %}
            <span class="error">Feld Benutzername darf nicht leer sein.</span>
        {% endif %}
        <h3>{{ customer }}, {{ customer.email }}</h3>
        <div class="frm_item">
            <label for="username">Benutzer: </label><input type="text" name="username" value="{{ customer.user.username }}" id="id_username">
        </div>
        {% csrf_token %}
        <input type="hidden" name="customer_id" value="{{ customer.id }}" id="customer_id" />
        <button type="submit">Speichern</button>
    </form>
</div>
<div id="change_password" class="custom_tab{% if visible != 'change_password' %} invisible{% endif %}">
    {% if password_changed %}
        <span class="success">Passwort geändert.</span>
    {% endif %}
    <form action="" method="post" id="change_customer_password">
        {% if password_to_short %}
            <span class="error">Feld Passwort darf nicht leer sein.</span>
        {% endif %}
        <h3>{{ customer }}, {{ customer.email }}</h3>
        <div class="frm_item">
            <label for="id_password">Passwort: </label><input type="text" name="password" value="" id="id_password">
            <button id="btn_random_password" type="button">Zufälliges Passwort</button>
        </div>
        {% csrf_token %}
        <input type="hidden" name="customer_id" value="{{ customer.id }}" id="customer_id" />
        <input type="hidden" name="toemail" value="0" id="toemail" />
        <button id="btn_basic_password" type="submit">Speichern</button>
        {% if customer.email %}
            <button id="btn_toemail_password" type="submit">Speichern + Passwort per E-Mail senden</button>
        {% endif %}
    </form>
</div>
<div id="delete_login" class="custom_tab{% if visible != 'delete_login' %} invisible{% endif %}">
    <br />  
    <button id="btn_remove_login" type="button">Login löschen</button>
</div>

<script type="text/javascript">
jq = '';
function close_event(e){
    jq('#overlay').remove();
    jq('#my_prompt').remove();
    jq('#btn_cancle').unbind('click');
    jq('#btn_close').unbind('click');
}

function setup_form($){
    jq = $;
    $('#btn_close').click(close_event);
    
    $('.btn_custom_tab').click(function(){
        var tab_id = $(this).attr('id').replace('btn_', '');
        $('.btn_custom_tab').removeClass('selected');
        $(this).addClass('selected');
        $('.custom_tab').addClass('invisible');
        $('#'+tab_id).removeClass('invisible');
    });
    
    $('#btn_random_password').click(function(){
        $.get("/admin/random_password/", function(data){
            $('#id_password').attr('value', data);
        })
    });
    
    $('#btn_basic_password').click(function(){
        $('#toemail').attr('value', '0');
    });
    
    $('#btn_toemail_password').click(function(){
        $('#toemail').attr('value', '1');
    });
    
    $('#change_customer_login').submit(function(e){
        e.preventDefault();
        var id = $('#customer_id').attr('value');
        var username = $('#id_username').attr('value');
        
        $.post("/admin/change_customer_login/?id="+id, $('#change_customer_login').serialize(), function(data){
            // if login created
            if($('<div></div>').append(data).find('.success').length > 0){
                $('#cl'+id).html(username);
            }
            set_prompt_body(data, $);
        });
    });
    
    $('#change_customer_password').submit(function(e){
        e.preventDefault();
        var id = $('#customer_id').attr('value');
        
        $.post("/admin/change_customer_password/?id="+id, $('#change_customer_password').serialize(), function(data){
            set_prompt_body(data, $);
        });
    });
    
    $('#btn_remove_login').click(function(){
        var id = $('#customer_id').attr('value');
        
        var r = confirm("Wollen Sie das Login wirklich löschen?");
        if (r == true) {
            $.get("/admin/delete_customer_login/?id="+id, function(data){
                if($('<div></div>').append(data).find('.success').length > 0){
                    $('#cl'+id).html('Login anlegen');
                }
                
                set_prompt_body(data, $);
            });
        }
    });
}



function set_prompt_body(data, $){
    $('#prompt_body').html(data);    
    setup_form($);
}

function init($){
    setup_form($);
}
</script>

kuechengeister/templates/kg/admin/rechnung_index.html
{% extends "admin_copies/change_list.html" %}
{% load i18n %}
{% load fieldtags %}
{% load my_templatetags %}
{% load url from future %}


{% block content %}
  {% with_setting CANTEEN_MODE as CANTEEN_MODE %}

  <div id="content-main">

    <h1>Rechnungen, SEPA, CSV</h1>
    
	<br />
 

  	
  	{% if error %}
		<div class="error">Fehler: {{error}}</div>
		<br />
	{% endif %}
  	
  	
  	{% if form_invoice.errors %}
		<div class="warning"><p>Es sind Fehler aufgetreten. Bitte korrigieren Sie die markierten Felder.</p></div>
		<br />
	{% endif %}
  	
  	<form action="{% url 'kg.views_admin.rechnung_index' %}" method="post" class="yform">
  		
  		{% csrf_token %}
  		
	   {% if form_invoice.non_field_errors %}{{ form_invoice.non_field_errors }}{% endif %}  
	   {% for fieldset in form_invoice.fieldsets %}  
	     <fieldset class="{{ fieldset.classes }}">  
	       {% if fieldset.legend %}  
	         <legend>{{ fieldset.legend }}</legend>  
	       {% endif %}  
	       {% if fieldset.description %}  
	         <div class="description">{{ fieldset.description }}</div>  
	       {% endif %}  
	         
	         <table class="invisible">
	         {% for field in fieldset %}  
	           {% if field.is_hidden %}  
	             {{ field }}  
	           {% else %}
	           		<tr>  
		       		  <td class="align-right valign-middle">{{ field.label_tag }}</td>
		         	  <td class="align-left valign-middle">{{ field }}</td>
		         	<tr>       
	           {% endif %}  
	         {% endfor %}
	         </table>
	       
	     </fieldset>  
	   {% endfor %}
   
		<input type="submit" value="Herunterladen" />
	</form>
    
    <br />
    <br />
    <br />  
    
    <form action="{% url 'kg.views_admin.rechnung_download' %}" method="get" class="yform">
    
    	<fieldset class="module aligned">  
	         
	         <legend>Rechnung für {% if CANTEEN_MODE %}einzelnen Mitarbeiter{% else %}einzelnes Kind{% endif %} herunterladen</legend>

	         <table class="invisible">
           		<tbody>
           			<tr>  
	       		  		<td class="align-right valign-middle">
	       		  			<label for="id_month">Monat</label>
	       		  		</td>
	         	  		<td class="align-left valign-middle">
	         	  			<select name="month" id="id_month">
	         	  				{% for month in months %}
									<option value="{{month}}" {% if month == last_of_last_month.month %}selected="selected"{% endif %}>{{month|stringformat:"02d"}}</option>
								{% endfor %}
							</select>
						</td>
	         		</tr>
	      			<tr>  
	       		  		<td class="align-right valign-middle">
	       		  			<label for="id_year">Jahr</label>
	       		  		</td>
	         	  		<td class="align-left valign-middle">
	         	  			<select name="year" id="id_year">
								{% for year in years %}
									<option value="{{year.year}}" {% if year.year == last_of_last_month.year %}selected="selected"{% endif %}>{{year.year}}</option>
								{% endfor %}
							</select>
						</td>
	         		</tr>
	         		<tr>  
	       		  		<td class="align-right valign-middle">
	       		  			<label for="id_child">{% if CANTEEN_MODE %}Mitarbeiter{% else %}Kinder{% endif %}</label>
	       		  		</td>
	         	  		<td class="align-left valign-middle">
	         	  			<select name="child_id" id="id_child">
								{% for child in children %}
									<option value="{{child.id}}">{{child}}</option>
								{% endfor %}
							</select>
						</td>
	         		</tr>
	         	</tbody>
			</table>
	       
	     </fieldset>
  
    	<input type="submit" value="Herunterladen" />
    	
	</form>

    <br />
    <br />
    <br />

    {%  if form_sepa %}

        <form action="{% url 'kg.views_admin.rechnung_index' %}" method="post" class="yform">

           {% csrf_token %}

           {% if form_sepa.non_field_errors %}{{ form_sepa.non_field_errors }}{% endif %}
           {% for fieldset in form_sepa.fieldsets %}
             <fieldset class="{{ fieldset.classes }}">
               {% if fieldset.legend %}
                 <legend>{{ fieldset.legend }}</legend>
               {% endif %}
               {% if fieldset.description %}
                 <div class="description">{{ fieldset.description }}</div>
               {% endif %}

                 <table class="invisible">
                 {% for field in fieldset %}
                   {% if field.is_hidden %}
                     {{ field }}
                   {% else %}
                        <tr>
                          <td class="align-right valign-middle">{{ field.label_tag }}</td>
                          <td class="align-left valign-middle">{{ field }}</td>
                        <tr>
                   {% endif %}
                 {% endfor %}
                 </table>

             </fieldset>
           {% endfor %}

            <input type="submit" name="FRST" value="Erst-Lastschriften" />
            &nbsp;&nbsp;&nbsp;
            <input type="submit" name="RCUR" value="Folge-Lastschriften" />
        </form>
        <br />
        <br />
        <br />

    {% endif %}

    {%  if form_fibu_bookings %}

        <form action="{{ form_fibu_bookings.action }}" method="post" class="yform">

           {% csrf_token %}

           {% if form_fibu_bookings.non_field_errors %}{{ form_fibu_bookings.non_field_errors }}{% endif %}
           {% for fieldset in form_fibu_bookings.fieldsets %}
             <fieldset class="{{ fieldset.classes }}">
               {% if fieldset.legend %}
                 <legend>{{ fieldset.legend }}</legend>
               {% endif %}
               {% if fieldset.description %}
                 <div class="description">{{ fieldset.description }}</div>
               {% endif %}

                 <table class="invisible">
                 {% for field in fieldset %}
                   {% if field.is_hidden %}
                     {{ field }}
                   {% else %}
                        <tr>
                          <td class="align-right valign-middle">{{ field.label_tag }}</td>
                          <td class="align-left valign-middle">{{ field }}</td>
                        <tr>
                   {% endif %}
                 {% endfor %}
                 </table>

             </fieldset>
           {% endfor %}

            <input type="submit" value="Herunterladen" />
            &nbsp;&nbsp;&nbsp;
        </form>
        <br />
        <br />
        <br />

    {% endif %}

    {% if form_fibu_debtors %}
        <form action="{{ form_fibu_debtors.action }}" method="post" class="yform">

            {% csrf_token %}

           {% if form_fibu_debtors.non_field_errors %}{{ form_fibu_debtors.non_field_errors }}{% endif %}
           {% for fieldset in form_fibu_debtors.fieldsets %}
             <fieldset class="{{ fieldset.classes }}">
               {% if fieldset.legend %}
                 <legend>{{ fieldset.legend }}</legend>
               {% endif %}
               {% if fieldset.description %}
                 <div class="description">{{ fieldset.description }}</div>
               {% endif %}

                 <table class="invisible">
                 {% for field in fieldset %}
                   {% if field.is_hidden %}
                     {{ field }}
                   {% else %}
                        <tr>
                          <td class="align-right valign-middle">{{ field.label_tag }}</td>
                          <td class="align-left valign-middle">{{ field }}</td>
                        <tr>
                   {% endif %}
                 {% endfor %}
                 </table>

             </fieldset>
           {% endfor %}

            <input type="submit" value="Herunterladen" />
        </form>

        <br />
        <br />
        <br />

    {% endif %}


    <form action="{% url 'kg.views_admin.rechnung_index' %}" method="post" class="yform">

        {% csrf_token %}

       {% if form_taxcsv.non_field_errors %}{{ form_taxcsv.non_field_errors }}{% endif %}
       {% for fieldset in form_taxcsv.fieldsets %}
         <fieldset class="{{ fieldset.classes }}">
           {% if fieldset.legend %}
             <legend>{{ fieldset.legend }}</legend>
           {% endif %}
           {% if fieldset.description %}
             <div class="description">{{ fieldset.description }}</div>
           {% endif %}

             <table class="invisible">
             {% for field in fieldset %}
               {% if field.is_hidden %}
                 {{ field }}
               {% else %}
                    <tr>
                      <td class="align-right valign-middle">{{ field.label_tag }}</td>
                      <td class="align-left valign-middle">{{ field }}</td>
                    <tr>
               {% endif %}
             {% endfor %}
             </table>

         </fieldset>
       {% endfor %}

        <input type="submit" value="Herunterladen" />
    </form>
    <br />
    <br />
    <br />


  </div>
{% endblock %}

kuechengeister/templates/kg/admin/sepa_debit_download.html
{% extends "admin/change_list.html" %} 
{% load i18n %}
{% load url from future %}


{% block content %}
  <div id="content-main">



    
  </div>
{% endblock %}

kuechengeister/templates/kg/admin/statistik_index.html
{% extends "admin_copies/change_list.html" %}
{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block content %}
  <div id="content-main">

    <h1>Monatsstatistik</h1>
    
    <br />

    <form action="{% url 'kg.views_admin.statistik_index' %}" method="get">
    	{% csrf_token %}
		<table class="invisible">
		<tr>
    	 {% for fieldset in form.fieldsets %}  
     
	         {% for field in fieldset %}
	         	<td>  
	           {% if field.is_hidden %}  
	             {{ field }}  
	           {% else %}  
	         		{{ field.errors }}  
	         		{{ field.label_tag }}  
	         		{{ field }}     
	           {% endif %}
	           </td>  
	         {% endfor %}  
	   {% endfor %}
   		
   		<td><input type="submit" value="Ändern" /></td>
		</tr>
    	</table>
	</form>
    
	<h3>{{date|date:"m/Y"}}</h3>
	
	<table class="standard">
		<thead>
			<tr>
				<th></th>
				{% for mealtime in mealtimes %}
				<th class="align-center" colspan="2">{{mealtime.name}}</th>
				{% endfor %}	
			</tr>
            <tr>
				<th></th>
				{% for mealtime in mealtimes %}
				<th class="align-center">bestellt</th>
                <th class="align-center">ausgegeben</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			{% for row in csv_list %}
			<tr>
				<td class="align-left"><strong>{{row.facility.name}}</strong></td>
				
				{% for mealtime in row.mealtimes %}
					<td class="align-center">
                    	{% if  mealtime.sum_all > 0 %} {{mealtime.sum_all}} {% else  %} - {% endif %}
                    </td>
                    <td class="align-center">
                    	{% if  mealtime.sum_picked_up > 0 %} {{mealtime.sum_picked_up}} {% else  %} - {% endif %}
                    </td>
				{% endfor %}
			</tr>
			{% endfor %}
			
			<tr style="border-top:2px solid #BBB;">
				<td class="align-left"><strong>Gesamt</strong></td>
				{% for mealtime_totals in accumulus %}
					<td class="align-center">
                        <strong>
                        	{% if  mealtime_totals.all > 0 %} {{mealtime_totals.all}} {% else  %} - {% endif %}
                    	</strong>
                    </td>
                    <td class="align-center">
                        	{% if  mealtime_totals.picked_up > 0 %} {{mealtime_totals.picked_up}} {% else  %} - {% endif %}
                    </td>
				{% endfor %}
			</tr>
			
		</tbody>
	</table>
  
    <h3>Monatsstatistik Detail pro Einrichtung:</h3>
    <form id="month-stats-download" action="{% url 'reports:report_month_stats' %}" method="post">
        {% csrf_token %}
		<div class="form-control">
            <select name="facility" id="id-facility" class="facilities" size="10">
                {% for facility in facilities %}
                <option value="{{ facility.id }}">{{ facility.name }}</option>
                {% endfor %}
            </select>
        </div>
        Von: <input type="text" name="date_from" class="datepicker" value="01.{{date|date:'m.Y'}}" />
        Bis: <input type="text" name="date_to" class="datepicker" value="{{date|date:'d.m.Y'}}" />
        <input type="submit" value="XLSX abrufen" disabled />
    </form>
    <br /><br />
    
  </div>
{% endblock %}

{% block js %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/3.3.5/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'datepicker/js/bootstrap-datepicker.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'datepicker/locales/bootstrap-datepicker.de.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
{% endblock %}

{% block docreadyjs %}
    {{ block.super }}
    $('.datepicker').datepicker({format: 'dd.mm.yyyy', weekStart: 1, language: 'de', autoclose: true});
    $('#id-facility').bind('click change', function(e){
        if (this.value != null) {
            $(this).closest('form').find('input[type="submit"]').prop('disabled', false);
        }
    });
{% endblock docreadyjs %}